spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/cydeo/dev/user/**
          filters:
            - RewritePath=/cydeo/dev/user/(?<segment>.*),/$\{segment}
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/cydeo/dev/project/**
          filters:
            - RewritePath=/cydeo/dev/project/(?<segment>.*),/$\{segment}
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/cydeo/dev/task/**
          filters:
            - RewritePath=/cydeo/dev/task/(?<segment>.*),/$\{segment}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

server:
  port: 8762

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://localhost:${server.port}/actuator
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans



info:
  application:
    name: ${spring.application.name}
    description: Ticketing Application
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'
